# Generated by Django 2.1.3 on 2019-01-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0002_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('formal', models.CharField(max_length=200)),
                ('test', models.CharField(max_length=200)),
            ],
        ),
    ]
