# Generated by Django 2.1.3 on 2019-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0003_createurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='createurl',
            name='createTime',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
